### ISSUE TITLE
Convert dictionary files to YAML

### ISSUE THREAD

**Issue by thomkeh** [thomkeh/amepd#2]
It would look like this:

```yaml
--- # all words starting with "A"
AABERG: AA1 B AXR G # asdf
AACHEN: AA1 K AX N
AACHENER: [AA1 K AX N AXR, AA1 K AX N AXR]
AAH: T     #asf
```

the parsed output is this:
```json
{
  "AACHEN": "AA1 K AX N", 
  "AABERG": "AA1 B AXR G", 
  "AAH": "T", 
  "AACHENER": [
    "AA1 K AX N AXR", 
    "AA1 K AX N AXR"
  ]
}
```
(source: https://yaml-online-parser.appspot.com )

Although, maybe don't use spaces in the pronunciation, but something like this:

```yaml
--- # all words starting with "A"
AABERG: AA1-B-AXR-G # asdf
AACHEN: AA1-K-AX-N
AACHENER: [AA1-K-AX-N-AXR, AA1-K-AX-N-AXR]
AAH: T     #asf
```

By the way,
> The official recommended filename extension for YAML files has been .yaml[8] since 2006.[9]
